CFLAGS="-Wall" -g

Prog=ex8

run: 
# @ hides bash commands used in the terminal when the label is called
	@echo "This is the file that we are running: $(Prog)"
	./$(Prog)

build: 
	make $(Prog)
# 	./$(Prog)
clean:
	rm -f $(Prog)

debug: 
	gdb ./$(Prog)




